x=input('Digite algo: ')
print('O tipo primitivo desse valor é:{}'.format(type(x)))
print('Só tem espaços? ',x.isspace())
print('É numérico? ',x.isnumeric())
print('É alfabético? ',x.isalpha())
print('É alfanumérico? ',x.isalnum())
print('É maiúscula? ',x.isupper())
print('É minúscula? ',x.islower())
print('Está capitalizada? ',x.istitle())
